# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Django app container to Azure App Service Container

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: boatregistry.azurecr.io
        username: 'boatregistry'
        password: ${{ secrets.BOATREGISTRY }}

    - run: |
        docker build . -t boatregistry.azurecr.io/unit-weather:latest
        docker push boatregistry.azurecr.io/unit-weather:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: weatherbot
          path: .
          
      - name: 'Deploy to Azure App Service Container'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'unit-weather'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'boatregistry.azurecr.io/unit-weather:latest'
