name: "Upload SARIF"

on:
  push: 
    branches: 
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all repos
      security-events: write
      # required for private repos only
      actions: read
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # path to sarif relative to root
          sarif_file: codeqloutput
          # optional category for the results
          # used to differentiate multiple results for one commit
          category: codeqlcli